using Naija.Grid.Net.Model;
using System.Collections.Generic;

namespace Naija.Grid.Net
{
    internal class NaijaGridService
    {
        public static List<State> GetAllStates()
        {
            return States;
        }

        private static readonly List<State> States = new List<State>
        {
            new State
            {
                Id = 1,
                Name = "Abia",
                Capital = "Umuahia",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Aba North"},
                    new LGA { Id = 2, Name = "Aba South"},
                    new LGA { Id = 3, Name = "Arochukwu"},
                    new LGA { Id = 4, Name = "Bende"},
                    new LGA { Id = 5, Name = "Ikwuano"},
                    new LGA { Id = 6, Name = "Isiala Ngwa North"},
                    new LGA { Id = 7, Name = "Isiala Ngwa South"},
                    new LGA { Id = 8, Name = "Isiukwuato"},
                    new LGA { Id = 9, Name = "Obingwa"},
                    new LGA { Id = 10, Name = "Ohafia"},
                    new LGA { Id = 11, Name = "Osisioma Ngwa"},
                    new LGA { Id = 12, Name = "Ugwunagbo"},
                    new LGA { Id = 13, Name = "Ukwa East"},
                    new LGA { Id = 14, Name = "Ukwa West"},
                    new LGA { Id = 15, Name = "Umuahia North"},
                    new LGA { Id = 16, Name = "Umuahia South"},
                    new LGA { Id = 17, Name = "Umu Nneochi"}
                }
            },
            new State
            {
                Id = 2,
                Name = "Adamawa",
                Capital = "Yola",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Demsa" },
                    new LGA { Id = 2, Name = "Fufure" },
                    new LGA { Id = 3, Name = "Ganye" },
                    new LGA { Id = 4, Name = "Gayuk" },
                    new LGA { Id = 5, Name = "Gombi" },
                    new LGA { Id = 6, Name = "Grie" },
                    new LGA { Id = 7, Name = "Hong" },
                    new LGA { Id = 8, Name = "Jada" },
                    new LGA { Id = 9, Name = "Larmurde" },
                    new LGA { Id = 10, Name = "Madagali" },
                    new LGA { Id = 11, Name = "Maiha" },
                    new LGA { Id = 12, Name = "Mayo Belwa" },
                    new LGA { Id = 13, Name = "Michika" },
                    new LGA { Id = 14, Name = "Mubi North" },
                    new LGA { Id = 15, Name = "Mubi South" },
                    new LGA { Id = 16, Name = "Numan" },
                    new LGA { Id = 17, Name = "Shelleng" },
                    new LGA { Id = 18, Name = "Song" },
                    new LGA { Id = 19, Name = "Toungo" },
                    new LGA { Id = 20, Name = "Yola North" },
                    new LGA { Id = 21, Name = "Yola South" }
                }
            },
            new State
            {
                Id = 3,
                Name = "Akwa Ibom",
                Capital = "Uyo",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Abak"},
                    new LGA { Id = 2, Name = "Eastern Obolo"},
                    new LGA { Id = 3, Name = "Eket"},
                    new LGA { Id = 4, Name = "Esit Eket"},
                    new LGA { Id = 5, Name = "Essien Udim"},
                    new LGA { Id = 6, Name = "Etim Ekpo"},
                    new LGA { Id = 7, Name = "Etinan"},
                    new LGA { Id = 8, Name = "Ibeno"},
                    new LGA { Id = 9, Name = "Ibesikpo Asutan"},
                    new LGA { Id = 10, Name = "Ibiono-Ibom"},
                    new LGA { Id = 11, Name = "Ikot Abasi"},
                    new LGA { Id = 12, Name = "Ika"},
                    new LGA { Id = 13, Name = "Ikono"},
                    new LGA { Id = 14, Name = "Ikot Ekpene"},
                    new LGA { Id = 15, Name = "Ini"},
                    new LGA { Id = 16, Name = "Mkpat-Enin"},
                    new LGA { Id = 17, Name = "Itu"},
                    new LGA { Id = 18, Name = "Mbo"},
                    new LGA { Id = 19, Name = "Nsit-Atai"},
                    new LGA { Id = 20, Name = "Nsit-Ibom"},
                    new LGA { Id = 21, Name = "Nsit-Ubium"},
                    new LGA { Id = 22, Name = "Obot Akara"},
                    new LGA { Id = 23, Name = "Okobo"},
                    new LGA { Id = 24, Name = "Onna"},
                    new LGA { Id = 25, Name = "Oron"},
                    new LGA { Id = 26, Name = "Udung-Uko"},
                    new LGA { Id = 27, Name = "Ukanafun"},
                    new LGA { Id = 28, Name = "Oruk Anam"},
                    new LGA { Id = 29, Name = "Uruan"},
                    new LGA { Id = 30, Name = "Urue-Offong/Oruko"},
                    new LGA { Id = 31, Name = "Uyo"},
                }
            },
            new State
            {
                Id = 4,
                Name = "Anambra",
                Capital = "Awka",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Aguata" },
                    new LGA { Id = 2, Name = "Anambra East" },
                    new LGA { Id = 3, Name = "Anaocha" },
                    new LGA { Id = 4, Name = "Awka North" },
                    new LGA { Id = 5, Name = "Anambra West" },
                    new LGA { Id = 6, Name = "Awka South" },
                    new LGA { Id = 7, Name = "Ayamelum" },
                    new LGA { Id = 8, Name = "Dunukofia" },
                    new LGA { Id = 9, Name = "Ekwusigo" },
                    new LGA { Id = 10, Name = "Idemili North" },
                    new LGA { Id = 11, Name = "Idemili South" },
                    new LGA { Id = 12, Name = "Ihiala" },
                    new LGA { Id = 13, Name = "Njikoka" },
                    new LGA { Id = 14, Name = "Nnewi North" },
                    new LGA { Id = 15, Name = "Nnewi South" },
                    new LGA { Id = 16, Name = "Ogbaru" },
                    new LGA { Id = 17, Name = "Onitsha North" },
                    new LGA { Id = 18, Name = "Onitsha South" },
                    new LGA { Id = 19, Name = "Orumba North" },
                    new LGA { Id = 20, Name = "Orumba South" },
                    new LGA { Id = 21, Name = "Oyi" },
                }
            },
            new State
            {
                Id = 5,
                Name = "Bauchi",
                Capital = "Bauchi",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Alkaleri" },
                    new LGA { Id = 2, Name = "Bauchi" },
                    new LGA { Id = 3, Name = "Bogoro" },
                    new LGA { Id = 4, Name = "Damban" },
                    new LGA { Id = 5, Name = "Darazo" },
                    new LGA { Id = 6, Name = "Dass" },
                    new LGA { Id = 7, Name = "Gamawa" },
                    new LGA { Id = 8, Name = "Ganjuwa" },
                    new LGA { Id = 9, Name = "Giade" },
                    new LGA { Id = 10, Name = "Itas/Gadau" },
                    new LGA { Id = 11, Name = "Jama'are" },
                    new LGA { Id = 12, Name = "Katagum" },
                    new LGA { Id = 13, Name = "Kirfi" },
                    new LGA { Id = 14, Name = "Misau" },
                    new LGA { Id = 15, Name = "Ningi" },
                    new LGA { Id = 16, Name = "Shira" },
                    new LGA { Id = 17, Name = "Tafawa Balewa" },
                    new LGA { Id = 18, Name = "Toro" },
                    new LGA { Id = 19, Name = "Warji" },
                    new LGA { Id = 20, Name = "Zaki" },
                }
            },
            new State
            {
                Id = 6,
                Name = "Bayelsa",
                Capital = "Yenagoa",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Brass" },
                    new LGA { Id = 2, Name = "Ekeremor" },
                    new LGA { Id = 3, Name = "Kolokuma/Opokuma" },
                    new LGA { Id = 4, Name = "Nembe" },
                    new LGA { Id = 5, Name = "Ogbia" },
                    new LGA { Id = 6, Name = "Sagbama" },
                    new LGA { Id = 7, Name = "Southern Ijaw" },
                    new LGA { Id = 8, Name = "Yenagoa" },
                }
            },
            new State
            {
                Id = 7,
                Name = "Benue",
                Capital = "Yenagoa",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Agatu" },
                    new LGA { Id = 2, Name = "Apa" },
                    new LGA { Id = 3, Name = "Ado" },
                    new LGA { Id = 4, Name = "Buruku" },
                    new LGA { Id = 5, Name = "Gboko" },
                    new LGA { Id = 6, Name = "Guma" },
                    new LGA { Id = 7, Name = "Gwer East" },
                    new LGA { Id = 8, Name = "Gwer West" },
                    new LGA { Id = 9, Name = "Katsina-Ala" },
                    new LGA { Id = 10, Name = "Konshisha" },
                    new LGA { Id = 11, Name = "Kwande" },
                    new LGA { Id = 12, Name = "Logo" },
                    new LGA { Id = 13, Name = "Makurdi" },
                    new LGA { Id = 14, Name = "Obi" },
                    new LGA { Id = 15, Name = "Ogbadibo" },
                    new LGA { Id = 16, Name = "Ohimini" },
                    new LGA { Id = 17, Name = "Oju" },
                    new LGA { Id = 18, Name = "Okpokwu" },
                    new LGA { Id = 19, Name = "Oturkpo" },
                    new LGA { Id = 20, Name = "Tarka" },
                    new LGA { Id = 21, Name = "Ukum" },
                    new LGA { Id = 22, Name = "Ushongo" },
                    new LGA { Id = 23, Name = "Vandeikya" },
                }
            },
            new State
            {
                Id = 8,
                Name = "Borno",
                Capital = "Maiduguri",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Abadam" },
                    new LGA { Id = 2, Name = "Askira/Uba" },
                    new LGA { Id = 3, Name = "Bama" },
                    new LGA { Id = 4, Name = "Bayo" },
                    new LGA { Id = 5, Name = "Biu" },
                    new LGA { Id = 6, Name = "Chibok" },
                    new LGA { Id = 7, Name = "Damboa" },
                    new LGA { Id = 8, Name = "Dikwa" },
                    new LGA { Id = 9, Name = "Guzamala" },
                    new LGA { Id = 10, Name = "Gubio" },
                    new LGA { Id = 11, Name = "Hawul" },
                    new LGA { Id = 12, Name = "Gwoza" },
                    new LGA { Id = 13, Name = "Jere" },
                    new LGA { Id = 14, Name = "Kaga" },
                    new LGA { Id = 15, Name = "Kala/Balge" },
                    new LGA { Id = 16, Name = "Konduga" },
                    new LGA { Id = 17, Name = "Kukawa" },
                    new LGA { Id = 18, Name = "Kwaya Kusar" },
                    new LGA { Id = 19, Name = "Mafa" },
                    new LGA { Id = 20, Name = "Magumeri" },
                    new LGA { Id = 21, Name = "Maiduguri" },
                    new LGA { Id = 22, Name = "Mobbar" },
                    new LGA { Id = 23, Name = "Marte" },
                    new LGA { Id = 24, Name = "Monguno" },
                    new LGA { Id = 25, Name = "Ngala" },
                    new LGA { Id = 26, Name = "Nganzai" },
                    new LGA { Id = 27, Name = "Shani" },
                }
            },
            new State
            {
                Id = 9,
                Name = "Cross River",
                Capital = "Calabar",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Abi" },
                    new LGA { Id = 2, Name = "Akamkpa" },
                    new LGA { Id = 3, Name = "Akpabuyo" },
                    new LGA { Id = 4, Name = "Bakassi" },
                    new LGA { Id = 5, Name = "Bekwarra" },
                    new LGA { Id = 6, Name = "Biase" },
                    new LGA { Id = 7, Name = "Boki" },
                    new LGA { Id = 8, Name = "Calabar Municipal" },
                    new LGA { Id = 9, Name = "Calabar South" },
                    new LGA { Id = 10, Name = "Etung" },
                    new LGA { Id = 11, Name = "Ikom" },
                    new LGA { Id = 12, Name = "Obanliku" },
                    new LGA { Id = 13, Name = "Obubra" },
                    new LGA { Id = 14, Name = "Obudu" },
                    new LGA { Id = 15, Name = "Odukpani" },
                    new LGA { Id = 16, Name = "Ogoja" },
                    new LGA { Id = 17, Name = "Yakuur" },
                    new LGA { Id = 18, Name = "Yala" },
                }
            },
            new State
            {
                Id = 10,
                Name = "Delta",
                Capital = "Asaba",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Aniocha North" },
                    new LGA { Id = 2, Name = "Aniocha South" },
                    new LGA { Id = 3, Name = "Bomadi" },
                    new LGA { Id = 4, Name = "Burutu" },
                    new LGA { Id = 5, Name = "Ethiope West" },
                    new LGA { Id = 6, Name = "Ethiope East" },
                    new LGA { Id = 7, Name = "Ika North East" },
                    new LGA { Id = 8, Name = "Ika South" },
                    new LGA { Id = 9, Name = "Isoko North" },
                    new LGA { Id = 10, Name = "Isoko South" },
                    new LGA { Id = 11, Name = "Ndokwa East" },
                    new LGA { Id = 12, Name = "Ndokwa West" },
                    new LGA { Id = 13, Name = "Okpe" },
                    new LGA { Id = 14, Name = "Oshimili North" },
                    new LGA { Id = 15, Name = "Oshimili South" },
                    new LGA { Id = 16, Name = "Patani" },
                    new LGA { Id = 17, Name = "Sapele" },
                    new LGA { Id = 18, Name = "Udu" },
                    new LGA { Id = 19, Name = "Ughelli North" },
                    new LGA { Id = 20, Name = "Ukwuani" },
                    new LGA { Id = 21, Name = "Ughelli South" },
                    new LGA { Id = 22, Name = "Uvwie" },
                    new LGA { Id = 23, Name = "Warri North" },
                    new LGA { Id = 24, Name = "Warri South" },
                    new LGA { Id = 25, Name = "Warri South West" },
                }
            },
            new State
            {
                Id = 11,
                Name = "Ebonyi",
                Capital = "Abakaliki",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Abakaliki" },
                    new LGA { Id = 2, Name = "Afikpo North" },
                    new LGA { Id = 3, Name = "Ebonyi" },
                    new LGA { Id = 4, Name = "Afikpo South" },
                    new LGA { Id = 5, Name = "Ezza North" },
                    new LGA { Id = 6, Name = "Ikwo" },
                    new LGA { Id = 7, Name = "Ezza South" },
                    new LGA { Id = 8, Name = "Ivo" },
                    new LGA { Id = 9, Name = "Ishielu" },
                    new LGA { Id = 10, Name = "Izzi" },
                    new LGA { Id = 11, Name = "Ohaozara" },
                    new LGA { Id = 12, Name = "Ohaukwu" },
                    new LGA { Id = 13, Name = "Onicha" },
                }
            },
            new State
            {
                Id = 12,
                Name = "Edo",
                Capital = "Benin City",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Akoko-Edo" },
                    new LGA { Id = 2, Name = "Egor" },
                    new LGA { Id = 3, Name = "Esan Central" },
                    new LGA { Id = 4, Name = "Esan North-East" },
                    new LGA { Id = 5, Name = "Esan South-East" },
                    new LGA { Id = 6, Name = "Esan West" },
                    new LGA { Id = 7, Name = "Etsako Central" },
                    new LGA { Id = 8, Name = "Etsako East" },
                    new LGA { Id = 9, Name = "Etsako West" },
                    new LGA { Id = 10, Name = "Igueben" },
                    new LGA { Id = 11, Name = "Ikpoba Okha" },
                    new LGA { Id = 12, Name = "Orhionmwon" },
                    new LGA { Id = 13, Name = "Oredo" },
                    new LGA { Id = 14, Name = "Ovia North-East" },
                    new LGA { Id = 15, Name = "Ovia South-West" },
                    new LGA { Id = 16, Name = "Owan East" },
                    new LGA { Id = 17, Name = "Owan West" },
                    new LGA { Id = 18, Name = "Uhunmwonde" },
                }
            },
            new State
            {
                Id = 13,
                Name = "Ekiti",
                Capital = "Ado Ekiti",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Ado Ekiti" },
                    new LGA { Id = 2, Name = "Efon" },
                    new LGA { Id = 3, Name = "Ekiti East" },
                    new LGA { Id = 4, Name = "Ekiti South-West" },
                    new LGA { Id = 5, Name = "Ekiti West" },
                    new LGA { Id = 6, Name = "Emure" },
                    new LGA { Id = 7, Name = "Gbonyin" },
                    new LGA { Id = 8, Name = "Ido Osi" },
                    new LGA { Id = 9, Name = "Ijero" },
                    new LGA { Id = 10, Name = "Ikere" },
                    new LGA { Id = 11, Name = "Ilejemeje" },
                    new LGA { Id = 12, Name = "Irepodun/Ifelodun" },
                    new LGA { Id = 13, Name = "Ikole" },
                    new LGA { Id = 14, Name = "Ise/Orun" },
                    new LGA { Id = 15, Name = "Moba" },
                    new LGA { Id = 16, Name = "Oye" },
                }
            },
            new State
            {
                Id = 14,
                Name = "Enugu",
                Capital = "Enugu",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Awgu" },
                    new LGA { Id = 2, Name = "Aninri" },
                    new LGA { Id = 3, Name = "Enugu East" },
                    new LGA { Id = 4, Name = "Enugu North" },
                    new LGA { Id = 5, Name = "Ezeagu" },
                    new LGA { Id = 6, Name = "Enugu South" },
                    new LGA { Id = 7, Name = "Igbo Etiti" },
                    new LGA { Id = 8, Name = "Igbo Eze North" },
                    new LGA { Id = 9, Name = "Igbo Eze South" },
                    new LGA { Id = 10, Name = "Isi Uzo" },
                    new LGA { Id = 11, Name = "Nkanu East" },
                    new LGA { Id = 12, Name = "Nkanu West" },
                    new LGA { Id = 13, Name = "Nsukka" },
                    new LGA { Id = 14, Name = "Udenu" },
                    new LGA { Id = 15, Name = "Oji River" },
                    new LGA { Id = 16, Name = "Uzo Uwani" },
                    new LGA { Id = 17, Name = "Udi" },
                }
            },
            new State
            {
                Id = 15,
                Name = "Gombe",
                Capital ="Gombe",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Akko" },
                    new LGA { Id = 2, Name = "Balanga" },
                    new LGA { Id = 3, Name = "Billiri" },
                    new LGA { Id = 4, Name = "Dukku" },
                    new LGA { Id = 5, Name = "Funakaye" },
                    new LGA { Id = 6, Name = "Gombe" },
                    new LGA { Id = 7, Name = "Kaltungo" },
                    new LGA { Id = 8, Name = "Kwami" },
                    new LGA { Id = 9, Name = "Nafada" },
                    new LGA { Id = 10, Name = "Shongom" },
                    new LGA { Id = 11, Name = "Yamaltu/Deba" },
                }
            },
            new State
            {
                Id = 16,
                Name = "Imo",
                Capital = "Owerri",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Aboh Mbaise" },
                    new LGA { Id = 2, Name = "Ahiazu Mbaise" },
                    new LGA { Id = 3, Name = "Ehime Mbano" },
                    new LGA { Id = 4, Name = "Ezinihitte" },
                    new LGA { Id = 5, Name = "Ideato North" },
                    new LGA { Id = 6, Name = "Ideato South" },
                    new LGA { Id = 7, Name = "Ihitte/Uboma" },
                    new LGA { Id = 8, Name = "Ikeduru" },
                    new LGA { Id = 9, Name = "Isiala Mbano" },
                    new LGA { Id = 10, Name = "Mbaitoli" },
                    new LGA { Id = 11, Name = "Isu" },
                    new LGA { Id = 12, Name = "Ngor Okpala" },
                    new LGA { Id = 13, Name = "Njaba" },
                    new LGA { Id = 14, Name = "Nkwerre" },
                    new LGA { Id = 15, Name = "Nwangele" },
                    new LGA { Id = 16, Name = "Obowo" },
                    new LGA { Id = 17, Name = "Oguta" },
                    new LGA { Id = 18, Name = "Ohaji/Egbema" },
                    new LGA { Id = 19, Name = "Okigwe" },
                    new LGA { Id = 20, Name = "Orlu" },
                    new LGA { Id = 21, Name = "Orsu" },
                    new LGA { Id = 22, Name = "Oru East" },
                    new LGA { Id = 23, Name = "Oru West" },
                    new LGA { Id = 24, Name = "Owerri Municipal" },
                    new LGA { Id = 25, Name = "Owerri North" },
                    new LGA { Id = 26, Name = "Unuimo" },
                    new LGA { Id = 27, Name = "Owerri West" },
                }
            },
            new State
            {
                Id = 17,
                Name = "Jigawa",
                Capital = "Dutse",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Auyo" },
                    new LGA { Id = 2, Name = "Babura" },
                    new LGA { Id = 3, Name = "Buji" },
                    new LGA { Id = 4, Name = "Biriniwa" },
                    new LGA { Id = 5, Name = "Birnin Kudu" },
                    new LGA { Id = 6, Name = "Dutse" },
                    new LGA { Id = 7, Name = "Gagarawa" },
                    new LGA { Id = 8, Name = "Garki" },
                    new LGA { Id = 9, Name = "Gumel" },
                    new LGA { Id = 10, Name = "Guri" },
                    new LGA { Id = 11, Name = "Gwaram" },
                    new LGA { Id = 12, Name = "Gwiwa" },
                    new LGA { Id = 13, Name = "Hadejia" },
                    new LGA { Id = 14, Name = "Jahun" },
                    new LGA { Id = 15, Name = "Kafin Hausa" },
                    new LGA { Id = 16, Name = "Kazaure" },
                    new LGA { Id = 17, Name = "Kiri Kasama" },
                    new LGA { Id = 18, Name = "Kiyawa" },
                    new LGA { Id = 19, Name = "Kaugama" },
                    new LGA { Id = 20, Name = "Maigatari" },
                    new LGA { Id = 21, Name = "Malam Madori" },
                    new LGA { Id = 22, Name = "Miga" },
                    new LGA { Id = 23, Name = "Sule Tankarkar" },
                    new LGA { Id = 24, Name = "Roni" },
                    new LGA { Id = 25, Name = "Ringim" },
                    new LGA { Id = 26, Name = "Yankwashi" },
                    new LGA { Id = 27, Name = "Taura" },
                }
            },
            new State
            {
                Id = 18,
                Name = "Kaduna",
                Capital = "Kaduna",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Birnin Gwari" },
                    new LGA { Id = 2, Name = "Chikun" },
                    new LGA { Id = 3, Name = "Giwa" },
                    new LGA { Id = 4, Name = "Ikara" },
                    new LGA { Id = 5, Name = "Igabi" },
                    new LGA { Id = 6, Name = "Jaba" },
                    new LGA { Id = 7, Name = "Jema'a" },
                    new LGA { Id = 8, Name = "Kachia" },
                    new LGA { Id = 9, Name = "Kaduna North" },
                    new LGA { Id = 10, Name = "Kaduna South" },
                    new LGA { Id = 11, Name = "Kagarko" },
                    new LGA { Id = 12, Name = "Kajuru" },
                    new LGA { Id = 13, Name = "Kaura" },
                    new LGA { Id = 14, Name = "Kauru" },
                    new LGA { Id = 15, Name = "Kubau" },
                    new LGA { Id = 16, Name = "Kudan" },
                    new LGA { Id = 17, Name = "Lere" },
                    new LGA { Id = 18, Name = "Makarfi" },
                    new LGA { Id = 19, Name = "Sabon Gari" },
                    new LGA { Id = 20, Name = "Sanga" },
                    new LGA { Id = 21, Name = "Soba" },
                    new LGA { Id = 22, Name = "Zangon Kataf" },
                    new LGA { Id = 23, Name = "Zaria" },
                }
            },
            new State
            {
                Id = 19,
                Name = "Kano",
                Capital = "Kano",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Ajingi" },
                    new LGA { Id = 2, Name = "Albasu" },
                    new LGA { Id = 3, Name = "Bagwai" },
                    new LGA { Id = 4, Name = "Bebeji" },
                    new LGA { Id = 5, Name = "Bichi" },
                    new LGA { Id = 6, Name = "Bunkure" },
                    new LGA { Id = 7, Name = "Dala" },
                    new LGA { Id = 8, Name = "Dambatta" },
                    new LGA { Id = 9, Name = "Dawakin Kudu" },
                    new LGA { Id = 10, Name = "Dawakin Tofa" },
                    new LGA { Id = 11, Name = "Doguwa" },
                    new LGA { Id = 12, Name = "Fagge" },
                    new LGA { Id = 13, Name = "Gabasawa" },
                    new LGA { Id = 14, Name = "Garko" },
                    new LGA { Id = 15, Name = "Garun Mallam" },
                    new LGA { Id = 16, Name = "Gezawa" },
                    new LGA { Id = 17, Name = "Gaya" },
                    new LGA { Id = 18, Name = "Gwale" },
                    new LGA { Id = 19, Name = "Gwarzo" },
                    new LGA { Id = 20, Name = "Kabo" },
                    new LGA { Id = 21, Name = "Kano Municipal" },
                    new LGA { Id = 22, Name = "Karaye" },
                    new LGA { Id = 23, Name = "Kibiya" },
                    new LGA { Id = 24, Name = "Kiru" },
                    new LGA { Id = 25, Name = "Kumbotso" },
                    new LGA { Id = 26, Name = "Kunchi" },
                    new LGA { Id = 27, Name = "Kura" },
                    new LGA { Id = 28, Name = "Madobi" },
                    new LGA { Id = 29, Name = "Makoda" },
                    new LGA { Id = 30, Name = "Minjibir" },
                    new LGA { Id = 31, Name = "Nasarawa" },
                    new LGA { Id = 32, Name = "Rano" },
                    new LGA { Id = 33, Name = "Rimin Gado" },
                    new LGA { Id = 34, Name = "Rogo" },
                    new LGA { Id = 35, Name = "Shanono" },
                    new LGA { Id = 36, Name = "Takai" },
                    new LGA { Id = 37, Name = "Sumaila" },
                    new LGA { Id = 38, Name = "Tarauni" },
                    new LGA { Id = 39, Name = "Tofa" },
                    new LGA { Id = 40, Name = "Tsanyawa" },
                    new LGA { Id = 41, Name = "Tudun Wada" },
                    new LGA { Id = 42, Name = "Ungogo" },
                    new LGA { Id = 43, Name = "Warawa" },
                    new LGA { Id = 44, Name = "Wudil" },
                }
            }
            new State
            {
                Id = 20,
                Name = "Katsina",
                Capital = "Katsina",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Bakori" },
                    new LGA { Id = 2, Name = "Batagarawa" },
                    new LGA { Id = 3, Name = "Batsari" },
                    new LGA { Id = 4, Name = "Baure" },
                    new LGA { Id = 5, Name = "Bindawa" },
                    new LGA { Id = 6, Name = "Charanchi" },
                    new LGA { Id = 7, Name = "Danja" },
                    new LGA { Id = 8, Name = "Dandume" },
                    new LGA { Id = 9, Name = "Dan Musa" },
                    new LGA { Id = 10, Name = "Daura" },
                    new LGA { Id = 11, Name = "Dutsi" },
                    new LGA { Id = 12, Name = "Dutsin Ma" },
                    new LGA { Id = 13, Name = "Faskari" },
                    new LGA { Id = 14, Name = "Funtua" },
                    new LGA { Id = 15, Name = "Ingawa" },
                    new LGA { Id = 16, Name = "Jibia" },
                    new LGA { Id = 17, Name = "Kafur" },
                    new LGA { Id = 18, Name = "Kaita" },
                    new LGA { Id = 19, Name = "Kankara" },
                    new LGA { Id = 20, Name = "Kankia" },
                    new LGA { Id = 21, Name = "Katsina" },
                    new LGA { Id = 22, Name = "Kurfi" },
                    new LGA { Id = 23, Name = "Kusada" },
                    new LGA { Id = 24, Name = "Mai'Adua" },
                    new LGA { Id = 25, Name = "Malumfashi" },
                    new LGA { Id = 26, Name = "Mani" },
                    new LGA { Id = 27, Name = "Mashi" },
                    new LGA { Id = 28, Name = "Matazu" },
                    new LGA { Id = 29, Name = "Musawa" },
                    new LGA { Id = 30, Name = "Rimi" },
                    new LGA { Id = 31, Name = "Sabuwa" },
                    new LGA { Id = 32, Name = "Safana" },
                    new LGA { Id = 33, Name = "Sandamu" },
                    new LGA { Id = 34, Name = "Zango" },
                }
            }
            new State
            {
                Id = 21,
                Name = "Kebbi",
                Capital = "Birnin Kebbi",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Aleiro" },
                    new LGA { Id = 2, Name = "Argungu" },
                    new LGA { Id = 3, Name = "Arewa Dandi" },
                    new LGA { Id = 4, Name = "Augie" },
                    new LGA { Id = 5, Name = "Bagudo" },
                    new LGA { Id = 6, Name = "Birnin Kebbi" },
                    new LGA { Id = 7, Name = "Bunza" },
                    new LGA { Id = 8, Name = "Dandi" },
                    new LGA { Id = 9, Name = "Fakai" },
                    new LGA { Id = 10, Name = "Gwandu" },
                    new LGA { Id = 11, Name = "Jega" },
                    new LGA { Id = 12, Name = "Kalgo" },
                    new LGA { Id = 13, Name = "Koko/Besse" },
                    new LGA { Id = 14, Name = "Maiyama" },
                    new LGA { Id = 15, Name = "Ngaski" },
                    new LGA { Id = 16, Name = "Shanga" },
                    new LGA { Id = 17, Name = "Suru" },
                    new LGA { Id = 18, Name = "Sakaba" },
                    new LGA { Id = 19, Name = "Wasagu/Danko" },
                    new LGA { Id = 20, Name = "Yauri" },
                    new LGA { Id = 21, Name = "Zuru" },
                }
            }
            new State
            {
                Id = 22,
                Name = "Kogi",
                Capital = "Lokoja",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Ajaokuta" },
                    new LGA { Id = 2, Name = "Adavi" },
                    new LGA { Id = 3, Name = "Ankpa" },
                    new LGA { Id = 4, Name = "Bassa" },
                    new LGA { Id = 5, Name = "Dekina" },
                    new LGA { Id = 6, Name = "Ibaji" },
                    new LGA { Id = 7, Name = "Idah" },
                    new LGA { Id = 8, Name = "Igalamela Odolu" },
                    new LGA { Id = 9, Name = "Ijumu" },
                    new LGA { Id = 10, Name = "Kogi" },
                    new LGA { Id = 11, Name = "Kabba/Bunu" },
                    new LGA { Id = 12, Name = "Lokoja" },
                    new LGA { Id = 13, Name = "Ofu" },
                    new LGA { Id = 14, Name = "Mopa Muro" },
                    new LGA { Id = 15, Name = "Ogori/Magongo" },
                    new LGA { Id = 16, Name = "Okehi" },
                    new LGA { Id = 17, Name = "Okene" },
                    new LGA { Id = 18, Name = "Olamaboro" },
                    new LGA { Id = 19, Name = "Omala" },
                    new LGA { Id = 20, Name = "Yagba East" },
                    new LGA { Id = 21, Name = "Yagba West" },
                }
            },
            new State
            {
                Id = 23,
                Name = "Kwara",
                Capital = "Ilorin",
                LGAs = new List<LGA>
                {
                    new LGA { Id = 1, Name = "Asa" },
                    new LGA { Id = 2, Name = "Baruten" },
                    new LGA { Id = 3, Name = "Edu" },
                    new LGA { Id = 4, Name = "Ilorin East" },
                    new LGA { Id = 5, Name = "Ifelodun" },
                    new LGA { Id = 6, Name = "Ilorin South" },
                    new LGA { Id = 7, Name = "Ekiti Kwara State" },
                    new LGA { Id = 8, Name = "Ilorin West" },
                    new LGA { Id = 9, Name = "Irepodun" },
                    new LGA { Id = 10, Name = "Isin" },
                    new LGA { Id = 11, Name = "Kaiama" },
                    new LGA { Id = 12, Name = "Moro" },
                    new LGA { Id = 13, Name = "Offa" },
                    new LGA { Id = 14, Name = "Oke Ero" },
                    new LGA { Id = 15, Name = "Oyun" },
                    new LGA { Id = 16, Name = "Pategi" },
                }
            }




        };
    }
}
